name: Amazon Linux Workflow

on:
  push:
    branches:
      - main

jobs:
  amazon-linux-job:
    runs-on: self-hosted # Host runner (not Amazon Linux)
    container:
      image: amazonlinux:2023  # Use Amazon Linux 2023 container
    steps:
      - name: Install dependencies
        run: |
          yum update -y
          yum install -y htop
          htop --version

      - name: Checkout code
        uses: actions/checkout@v4
